version: '3.8'

services:
  fan-control:
    build: .
    container_name: fan_control_service
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "utility"
    runtime: nvidia
