services:
  fan-control:
    build: .
    image: fan_control:ipmi
    container_name: fan_control_service
    restart: unless-stopped
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["utility"]
    # Replaced `runtime: nvidia` with `--gpus all` for GPU configuration
